### ISSUE TITLE
Desugar other primitives into rand (or trace) + distribution

### ISSUE THREAD

**Issue by femtomc** [probcomp/TracedRandom.jl#1]
In terms of intercepting calls, it would actually be really convenient if we re-expressed each of the "compound" primitives (like `randn`) in terms of `rand` (or `trace`) and a distribution. This eliminates the extra step of inserting the distribution ([as currently required in Genify](https://github.com/probcomp/Genify.jl/blob/main/src/primitives.jl)) for other packages.

In simple terms, if we could express all of the new addressed primitives as `rand(:addr, D)` - I think it simplifies the interfaces which `Jaynes` or `Genify` needs to look at (e.g. for all of `TracedRandom` - we'd only need to look for the target primitive).

I suspect this is more difficult for things like `randperm` - which I'm conveniently ignoring for this issue.

**Comment by ztangent** [comment]
Just saw this! I think my issue with this is that it adds an unnecessary dependency on `Distributions.jl`, and I was thinking of keeping this package as lightweight as possible.

**Comment by femtomc** [comment]
@ztangent  Yep that makes sense!

I also realized I could solve my (library specific) issue with metaprogramming to define each TracedRandom exported primitive as a trace primitive in my architecture - so this is no big deal.

Closing.
